export const EVENT_TITLES: string[] = [
  "Incroyable !!",
  "C'est pas vrai...",
  "Vous le croyez ca ?",
  "C'est fou ce qui se passe !!",
  "Eh merde...",
  "C'est pas possible !!?",
  "Oh nan pas ca",
  "Pas de chance pour lui",
  "Le tournant de la course ?",
  "On croit rever",
  "Saperlipopette",
  "Non pas maintenant ??",
  "Petit souci sur la piste...",
  "Y'en a un qui est dans la merde",
  "Fin de course vraiment ?",
  "Incident sur un cheval !",
  "Aie aie aie....",
  "Ouuuuh",
  "Retournement de situation !!",
  "Comment c'est possible ?!",
  "Du jamais vu !",
  "J'hallucine...",
  "C'est la debandade !",
  "Le chaos s'installe !",
  "Personne ne s'y attendait !",
  "Tout s'effondre !",
  "La course bascule !",
  "Crise en direct !",
  "Mais qu'est-ce qui se passe ?!",
  "T'as vu ca toi ?!",
  "NON. NON. NON.",
  "Je reve ou quoi ?!",
  "C'est reel ca ?!",
  "Quelqu'un a vu ?!",
  "Attends... ATTENDS.",
  "Hein ?! Comment ?!",
  "Pincez-moi je dors",
  "C'est une blague ??",
  "Un drame est en cours...",
  "Ca tourne mal !",
  "Catastrophe sur la piste !",
  "Ca part en couille la...",
]

export const EVENT_DESCRIPTIONS: string[] = [
  "On dirait bien que ... s'est defequee dessus",
  "... vient de chuter ! Va-t-il se relever ?",
  "... vient de prendre un projectile, va-t-il reussir a continuer ?",
  "... respire mal, le soigneur lui donne de la ventoline !",
  "... perd de la vitesse, va-t-il repartir ?",
  "... a pris un molard sur la crignere... il faut lui enlever pour qu'il continue d'avancer",
  "... a oublie de fermer a clef sa voiture, va-t-il aller la fermer et perdre la course ?",
  "... s'est casse le tibia, est-ce qu'il peut encore finir la course ?",
  "... a perdu un sabot, va-t-il reussir a mettre celui de secours ?",
  "... a vu son ex dans les tribunes, il est trouble. Va-t-il rester solide mentalement ?",
  "... vient de se prendre un pigeon en pleine face, va-t-il retrouver sa trajectoire ?",
  "... s'est foule le poignet, le kine intervient d'urgence !",
  "... vient de perdre une oreille, va-t-il continuer avec une seule ?",
  "... a glisse sur une peau de banane, est-ce qu'il repart ?",
  "... s'est mordu la langue, il saigne abondamment !",
  "... a perdu sa selle en plein virage, va-t-il finir a poil ?",
  "... a les lacets defaits, va-t-il s'arreter pour les renouer ?",
  "... a oublie sa cravache au vestiaire, va-t-il faire demi-tour ?",
  "... a son GPS qui bug, il ne sait plus ou est l'arrivee !",
  "... a le slip qui descend, il doit s'arreter pour le remonter !",
  "... vient de recevoir un appel de sa mere, va-t-il decrocher ?",
  "... a repere un McDo sur le cote, va-t-il resister ?",
  "... consulte ses messages en courant, va-t-il rater un virage ?",
  "... a reconnu un pote dans les gradins, va-t-il aller lui dire bonjour ?",
  "... a oublie de couper le four chez lui, il hesite a rentrer de toute vitesse",
  "... regarde un reel depuis le depart, personne ne s'en etait rendu compte !",
  "... vient d'etre frappe par la foudre, va-t-il tenir le coup ?",
  "Un chien errant suit ... depuis 200 metres, va-t-il le semer ?",
  "Une mouche est entree dans la narine de ..., il s'arrete pour souffler ?",
  "... vient de marcher sur un herisson, aie ! Va-t-il lacher la course ?",
  "Un canard traverse la piste devant ..., va-t-il freiner ?",
  "Un mouton s'est attache a la queue de ..., il ralentit ! Ca va suffire ?",
  "... a une crampe au mollet gauche, le staff hesite a lui tendre une banane !",
  "... vient d'eternuer si fort qu'il a perdu 3 metres ! Va-t-il les recuperer ?",
  "... a le hoquet depuis le depart, ca le ralentit considerablement ! Il tient bon ?",
  "... transpire tellement qu'il est a deux doigts de glisser sur le ventre",
  "... vient d'etre contacte par la NASA, ils ont besoin de lui de toute urgence ! Il part ?",
  "... a recu sa convocation aux prud'hommes, il est sous le choc ! Va-t-il tenir le cap ?",
  "... est en train d'accoucher ! Va-t-on lancer le gosse en tribune ?",
  "... a ete reconnu par un paparazzi, il pose pour les photos ! Quand va-t-il s'arreter ?",
  "... vient d'etre elu maire de la ville, doit-il aller preter serment ?",
  "... a recu un texto lui annoncant qu'il a gagne au loto ! Il finit la course quand meme ?",
  "... vient de se souvenir qu'il a un exam demain matin, il veut aller reviser sur le champ",
  "... a commande une pizza qui vient d'arriver sur la piste, le livreur va-t-il le rattraper ?",
  "... entend sa chanson preferee et s'arrete pour danser ! La musique va-t-elle se couper ?",
  "... vient de trouver un billet de 50 euros sur la piste, va-t-il le ramasser ?",
]
